@ECHO OFF

SET SRCDIR=D:\INFINITT_LIB
SET DESTDIR=..\Runtime
SET DCMDLL_DIR=%SRCDIR%\INFINITT_LIB38_V9\DCMDLL\V2
SET LIBGEN_DIR=%SRCDIR%\INFINITT_LIB38_V9\LIBGEN\V1
SET DCMIMAGE_DIR=%SRCDIR%\INFINITT_LIB38_V9\DCMIMAGE\V2
SET EXCTRL_DIR=%SRCDIR%\EXCTRL\V1
SET JPEGPRO_DIR=%SRCDIR%\JPEGPRO\3.2.4
SET PICTOOL_DIR=%SRCDIR%\PICTOOL\V1
SET ETC_DIR=%SRCDIR%\ETC\V5



SET WINSYSDIR=C:\WINDOWS\System32
SET COPYOPT=/K /R /Y

SET ORA817_HOME=D:\ORACLE\ORA817
SET ORA920_HOME=D:\ORACLE\ORA920
SET ORA102_HOME=D:\ORACLE\ORA102
SET ORA111_HOME=D:\ORACLE\ORA111

REM	-------------------------------------------------------------------------------------------
REM	PostBuild.bat (dll(V9) update to runtime folder)
REM	-------------------------------------------------------------------------------------------

REM -- common files
REM XCOPY %WINSYSDIR%\MFC40.DLL					%DESTDIR% %COPYOPT%
REM XCOPY %WINSYSDIR%\MFC42.DLL					%DESTDIR% %COPYOPT%
REM XCOPY %WINSYSDIR%\MSVCRT.DLL				%DESTDIR% %COPYOPT%
REM XCOPY %WINSYSDIR%\MSVCIRT.DLL				%DESTDIR% %COPYOPT%
REM XCOPY %WINSYSDIR%\MSVCP60.DLL				%DESTDIR% %COPYOPT%

XCOPY %ORA920_HOME%\BIN\ORASQL9.dll				%DESTDIR% %COPYOPT%
XCOPY %ORA102_HOME%\BIN\ORASQL10.dll			%DESTDIR% %COPYOPT%
XCOPY %ORA111_HOME%\BIN\ORASQL11.dll			%DESTDIR% %COPYOPT% 


REM -- MFDCM files



REM -- DYNAZIP files
XCOPY %ETC_DIR%\dunzip32.dll					%DESTDIR% %COPYOPT%

XCOPY system_info.dll							%DESTDIR% %COPYOPT%

ECHO "PostBuild.bat (dll(V9) update to runtime folder)"